#server:
#  port: 8081
#  servlet:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssda?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: '12345678'
#  thymeleaf:
#    cache: 'false'
#
#  #spring data jpa ?
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#
#

# File upload related settings
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssda?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '12345678'
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  # Here are the custom properties
  item-img-location: /Users/pizza/Desktop/image/
  upload-path: file:/Users/pizza/Desktop/image/

